### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by compyy** [CheckPoint-APIs-Team/cp_mgmt_api_python_sdk#1]
Hello,

I am trying to find duplicate IPs on my R80.10 Management Server and getting following error when i run the script.

[Expert@P-WKG-VAP005:0]# $FWDIR/Python/bin/python find_dup_ip.py
Enter server IP address or hostname:localhost
Enter username: admin_ashfaquey
Enter password: 
       
Saving data to debug file api_calls.json

Traceback (most recent call last):
  File "find_dup_ip.py", line 93, in <module>
    main()
  File "find_dup_ip.py", line 58, in main
    exit(1)
  File "/home/admin/cp_mgmt_api_python_sdk-master/lib/mgmt_api.py", line 109, in __exit__
    self.save_debug_data()
  File "/home/admin/cp_mgmt_api_python_sdk-master/lib/mgmt_api.py", line 128, in save_debug_data
    out_file.write(json.dumps(self.api_calls, indent=4, sort_keys=True))
  File "/opt/CPsuite-R80/fw1/Python/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/opt/CPsuite-R80/fw1/Python/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
MemoryError

**Comment by compyy** [comment]
Just an update, i fixed it by editing:

mgmt_api.py line 128 --> 
#out_file.write(json.dumps(self.api_calls, indent=4, sort_keys=True))
json.dump(self.api_calls, out_file, indent=4, sort_keys=True)

it fixed the issue but still fails with following error.
Saving data to debug file api_calls.json

Traceback (most recent call last):
  File "find_dup_ip.py", line 93, in <module>
    main()
  File "find_dup_ip.py", line 67, in main
    ipaddr = host["ipv4-address"]
KeyError: 'ipv4-address'


The size of api_calls.json is 2.8GB.

**Comment by CheckPoint-APIs-Team** [comment]
Hi,
How many hosts do you have in you DB? Maybe we have a problem of memory usage here...
Thanks.

**Comment by compyy** [comment]
Hi,
Yes we have 3486 total host objects.

**Comment by CheckPoint-APIs-Team** [comment]
We will check this and inform this forum.
Thanks.

**Comment by compyy** [comment]
ok Thanks

**Comment by CheckPoint-APIs-Team** [comment]
Hi, we have just run this script on 15800 host objects, from Windows OS 7, 64 bit, 16 GB RAM, on R80.10 MDS environment.
Finished successfully, debug file 2.6 GB.
We checked with details level "standard" instead of "full" - this should be OK for you too (line 55). This will also reduce the debug file size. We will change the code for that.
On which OS did you run the script? Linux?
Regarding the second error - it seems that you have a corrupted data in one of your hosts.
We will modify the code not to crash in such scenario.

**Comment by CheckPoint-APIs-Team** [comment]
KeyError exception handled.
Now using details level "standard" for hosts query.

**Comment by compyy** [comment]
Hi, i ran this script on Linux with 2GB RAM, VM environment, i will try to increase the RAM to 4GB.

**Comment by CheckPoint-APIs-Team** [comment]
No need, the code fix is enough.
