### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by phandox** [CheckPoint-APIs-Team/cp_mgmt_api_python_sdk#2]
Hello,

do you plan supporting Python 3 with your SDK? Python 2.7 will go out of life in 2 years, it's time to move to Python 3, don't you think?

https://pythonclock.org/

Thanks.

**Comment by CheckPoint-APIs-Team** [comment]
Hi,
Yes, we are aware of this time line, but currently Check Point's management server supports Python 2.7.14,
and untill it is not upgraded, we are limitide to it.
